import type { Metadata } from "next";
import "./globals.css";
import BottomNav from "./components/BottomNav";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/rastikerdar/vazir-font@v30.1.0/dist/font-face.css"
        />
      </head>
      <body className={`antialiased pb-20`}>
        {children}
        <BottomNav />
      </body>
    </html>
  );
}
